function showMainMenu(fig)
    setappdata(fig, 'currentMenu', 'main');
    set(fig, 'Name', 'Masters of the Universe: Battleground');

    % Obtener dimensiones de la pantalla desde appdata
    screenWidth = getappdata(fig, 'screenWidth');
    screenHeight = getappdata(fig, 'screenHeight');

    delete(gca(fig));
    delete(findall(fig, 'Style', 'pushbutton'));

    ax = axes('Parent', fig, 'Position', [0, 0, 1, 1], ...
        'XTick', [], 'YTick', [], 'Box', 'off', 'XColor', 'none', 'YColor', 'none');
    images = getappdata(fig, 'images');
    try
        img = images.background;
        image(img, 'Parent', ax);
        ax.XLim = [0 size(img, 2)];
        ax.YLim = [0 size(img, 1)];
    catch e
        disp('Error al cargar la imagen de fondo bkg_intro.jpg: ');
        disp(e.message);
        set(ax, 'Color', [1 1 1]);
    end

    titleWidth = 700;
    titleHeight = 140;
    titleControl = uicontrol(fig, 'Style', 'pushbutton', ...
        'Position', [(screenWidth-titleWidth)/2, screenHeight-400, titleWidth, titleHeight], ...
        'CData', images.title, ...
        'Enable', 'inactive');

    buttonWidth = 400;
    buttonHeight = 80;
    totalButtonWidth = buttonWidth * 2 + 100;
    btnOption1 = uicontrol(fig, 'Style', 'pushbutton', ...
        'Position', [(screenWidth-totalButtonWidth)/2, screenHeight/2-40, buttonWidth, buttonHeight], ...
        'CData', images.button1, ...
        'Callback', @(~, ~)option1Callback(fig), ...
        'Tag', 'btnOption1');

    btnOption2 = uicontrol(fig, 'Style', 'pushbutton', ...
        'Position', [(screenWidth-totalButtonWidth)/2 + buttonWidth + 100, screenHeight/2-40, buttonWidth, buttonHeight], ...
        'CData', images.button2, ...
        'Callback', @(~, ~)option2Callback(fig), ...
        'Tag', 'btnOption2');

    btnExit = uicontrol(fig, 'Style', 'pushbutton', ...
        'Position', [screenWidth-340, 20, 320, 64], ...
        'CData', images.exit, ...
        'Callback', @(~, ~)exitCallback(fig), ...
        'Tag', 'btnExit');

    if isempty(getappdata(fig, 'bgMusicPlayer'))
        try
            audio = getappdata(fig, 'audio');
            musicVolume = getappdata(fig, 'musicVolume');
            bgMusicPlayer = audioplayer(audio.bgMusic * musicVolume, audio.bgFs);
            play(bgMusicPlayer);
            setappdata(fig, 'bgMusicPlayer', bgMusicPlayer);
            musicTimer = timer('ExecutionMode', 'fixedRate', 'Period', 1, ...
                'TimerFcn', @(~, ~)checkMusicLoop(fig), 'StartDelay', 0);
            start(musicTimer);
            setappdata(fig, 'musicTimer', musicTimer);
        catch e
            disp('Error al cargar o reproducir la música de fondo: ');
            disp(e.message);
        end
    end

    musicLabelControl = uicontrol(fig, 'Style', 'pushbutton', ...
        'Position', [20, 234, 320, 64], ...
        'CData', images.musicLabel, ...
        'Enable', 'inactive');
    btnMusicMinus = uicontrol(fig, 'Style', 'pushbutton', ...
        'Position', [20, 170, 98, 64], ...
        'CData', images.minus, ...
        'Callback', @(~, ~)musicMinusCallback(fig), ...
        'Tag', 'btnMusicMinus');
    musicVolumeLevel = round(getappdata(fig, 'musicVolume') * 100 / 10) * 10;
    imgMusicVolume = uicontrol(fig, 'Style', 'pushbutton', ...
        'Position', [118, 170, 124, 64], ...
        'CData', images.volumeLevels(musicVolumeLevel), ...
        'Enable', 'inactive', ...
        'Tag', 'imgMusicVolume');
    btnMusicPlus = uicontrol(fig, 'Style', 'pushbutton', ...
        'Position', [242, 170, 98, 64], ...
        'CData', images.plus, ...
        'Callback', @(~, ~)musicPlusCallback(fig), ...
        'Tag', 'btnMusicPlus');
    uistack(btnMusicMinus, 'top');
    uistack(imgMusicVolume, 'top');
    uistack(btnMusicPlus, 'top');

    sfxLabelControl = uicontrol(fig, 'Style', 'pushbutton', ...
        'Position', [20, 74, 320, 64], ...
        'CData', images.sfxLabel, ...
        'Enable', 'inactive');
    btnSfxMinus = uicontrol(fig, 'Style', 'pushbutton', ...
        'Position', [20, 10, 98, 64], ...
        'CData', images.minus, ...
        'Callback', @(~, ~)sfxMinusCallback(fig), ...
        'Tag', 'btnSfxMinus');
    sfxVolumeLevel = round(getappdata(fig, 'sfxVolume') * 100 / 10) * 10;
    imgSfxVolume = uicontrol(fig, 'Style', 'pushbutton', ...
        'Position', [118, 10, 124, 64], ...
        'CData', images.volumeLevels(sfxVolumeLevel), ...
        'Enable', 'inactive', ...
        'Tag', 'imgSfxVolume');
    btnSfxPlus = uicontrol(fig, 'Style', 'pushbutton', ...
        'Position', [242, 10, 98, 64], ...
        'CData', images.plus, ...
        'Callback', @(~, ~)sfxPlusCallback(fig), ...
        'Tag', 'btnSfxPlus');
    uistack(btnSfxMinus, 'top');
    uistack(imgSfxVolume, 'top');
    uistack(btnSfxPlus, 'top');

    btnVersion = uicontrol(fig, 'Style', 'pushbutton', ...
        'Position', [20, screenHeight-184, 320, 64], ...
        'CData', images.version, ...
        'Callback', @(~, ~)versionCallback(fig), ...
        'Tag', 'btnVersion');
    uistack(btnVersion, 'top');
    drawnow;
end